blank_issues_enabled: false
contact_links:
  - name: 💬 需要口头讨论？
    about: 对于架构上的重大改动，请先在群里或面对面沟通，或者直接联系 'QQMail:861749276@qq.com', 暂时不要直接开 Issue。
    url: https://github.com/oh-my-robot/oh-my-robot-framework