#ifndef __DM_MC_BOARD_PINMAP_H__
#define __DM_MC_BOARD_PINMAP_H__

#include "stm32h7xx_hal.h"

#define DM_MC_BOARD_HSE_VALUE_HZ 24000000UL

#define DM_MC_BOARD_USART1_TX_PORT GPIOA
#define DM_MC_BOARD_USART1_TX_PIN  GPIO_PIN_9
#define DM_MC_BOARD_USART1_RX_PORT GPIOA
#define DM_MC_BOARD_USART1_RX_PIN  GPIO_PIN_10

#define DM_MC_BOARD_USART2_TX_PORT GPIOD
#define DM_MC_BOARD_USART2_TX_PIN  GPIO_PIN_5
#define DM_MC_BOARD_USART2_RX_PORT GPIOD
#define DM_MC_BOARD_USART2_RX_PIN  GPIO_PIN_6
#define DM_MC_BOARD_USART2_DE_PORT GPIOD
#define DM_MC_BOARD_USART2_DE_PIN  GPIO_PIN_4

#define DM_MC_BOARD_USART3_TX_PORT GPIOD
#define DM_MC_BOARD_USART3_TX_PIN  GPIO_PIN_8
#define DM_MC_BOARD_USART3_RX_PORT GPIOD
#define DM_MC_BOARD_USART3_RX_PIN  GPIO_PIN_9
#define DM_MC_BOARD_USART3_DE_PORT GPIOB
#define DM_MC_BOARD_USART3_DE_PIN  GPIO_PIN_14

#define DM_MC_BOARD_UART5_RX_PORT GPIOD
#define DM_MC_BOARD_UART5_RX_PIN  GPIO_PIN_2

#define DM_MC_BOARD_UART7_TX_PORT GPIOE
#define DM_MC_BOARD_UART7_TX_PIN  GPIO_PIN_8
#define DM_MC_BOARD_UART7_RX_PORT GPIOE
#define DM_MC_BOARD_UART7_RX_PIN  GPIO_PIN_7

#define DM_MC_BOARD_UART8_TX_PORT GPIOE
#define DM_MC_BOARD_UART8_TX_PIN  GPIO_PIN_1
#define DM_MC_BOARD_UART8_RX_PORT GPIOE
#define DM_MC_BOARD_UART8_RX_PIN  GPIO_PIN_0

#define DM_MC_BOARD_UART9_TX_PORT GPIOD
#define DM_MC_BOARD_UART9_TX_PIN  GPIO_PIN_15
#define DM_MC_BOARD_UART9_RX_PORT GPIOD
#define DM_MC_BOARD_UART9_RX_PIN  GPIO_PIN_14

#define DM_MC_BOARD_USART10_TX_PORT GPIOE
#define DM_MC_BOARD_USART10_TX_PIN  GPIO_PIN_3
#define DM_MC_BOARD_USART10_RX_PORT GPIOE
#define DM_MC_BOARD_USART10_RX_PIN  GPIO_PIN_2

#define DM_MC_BOARD_WS2812_SPI_INSTANCE SPI6
#define DM_MC_BOARD_WS2812_GPIO_PORT    GPIOA
#define DM_MC_BOARD_WS2812_GPIO_PIN     GPIO_PIN_7

#define DM_MC_BOARD_BUZZER_TIM_INSTANCE TIM12
#define DM_MC_BOARD_BUZZER_TIM_CHANNEL  TIM_CHANNEL_2
#define DM_MC_BOARD_BUZZER_GPIO_PORT    GPIOB
#define DM_MC_BOARD_BUZZER_GPIO_PIN     GPIO_PIN_15

#define DM_MC_BOARD_KEY_GPIO_PORT GPIOA
#define DM_MC_BOARD_KEY_GPIO_PIN  GPIO_PIN_15

#define DM_MC_BOARD_CAN1_RX_PORT GPIOD
#define DM_MC_BOARD_CAN1_RX_PIN  GPIO_PIN_0
#define DM_MC_BOARD_CAN1_TX_PORT GPIOD
#define DM_MC_BOARD_CAN1_TX_PIN  GPIO_PIN_1

#define DM_MC_BOARD_CAN2_RX_PORT GPIOB
#define DM_MC_BOARD_CAN2_RX_PIN  GPIO_PIN_5
#define DM_MC_BOARD_CAN2_TX_PORT GPIOB
#define DM_MC_BOARD_CAN2_TX_PIN  GPIO_PIN_6

#define DM_MC_BOARD_CAN3_RX_PORT GPIOD
#define DM_MC_BOARD_CAN3_RX_PIN  GPIO_PIN_12
#define DM_MC_BOARD_CAN3_TX_PORT GPIOD
#define DM_MC_BOARD_CAN3_TX_PIN  GPIO_PIN_13

#define DM_MC_BOARD_POWER_5V_GPIO_PORT   GPIOC
#define DM_MC_BOARD_POWER_5V_GPIO_PIN    GPIO_PIN_15
#define DM_MC_BOARD_POWER_OUT1_GPIO_PORT GPIOC
#define DM_MC_BOARD_POWER_OUT1_GPIO_PIN  GPIO_PIN_14
#define DM_MC_BOARD_POWER_OUT2_GPIO_PORT GPIOC
#define DM_MC_BOARD_POWER_OUT2_GPIO_PIN  GPIO_PIN_13

#define DM_MC_BOARD_VBAT_ADC_GPIO_PORT GPIOC
#define DM_MC_BOARD_VBAT_ADC_GPIO_PIN  GPIO_PIN_4
#define DM_MC_BOARD_VBAT_ADC_INSTANCE  ADC1
#define DM_MC_BOARD_VBAT_ADC_CHANNEL   ADC_CHANNEL_4

#endif
